export const userRows = [
    { id: 1, 
      username: 'Jon Snow', 
      avatar: 'jon',
      email: 'joh.snow@gmail.com', 
      status:"active",
      transaction:"$839" },
    { id: 2, 
      username: 'Arya Stark', 
      avatar: 'Arya', 
      email: 'arya.stark@gmail.com', 
      status:"active",
      transaction:"$385" },
    { id: 3, 
      username: 'Sansa Stark', 
      avatar: 'sansa', 
      email: 'sansa.stark@gmail.com', 
      status:"active",
      transaction:"$8839" },
    { id: 4, 
      username: 'Bran Stark', 
      avatar: 'bran', 
      email: 'brank.stark@gmail.com', 
      status:"active",
      transaction:"$122" },
    { id: 5, 
      username: 'Samwell Tarly', 
      avatar: 'samwell', 
      email: 'samwell.tarly@gmail.com', 
      status:"active",
      transaction:"$738" },
  ];
  
  